### ISSUE TITLE
Refactor DataProcessor class

### ISSUE THREAD

**Issue by acsolle66** [Samyssmile/edux#108]
We need to change the parameter in the getColumnDataOf method within DataProcessor. Specifically, I suggest altering the parameter from ```String columnName``` to ```int columnIndex``` due to identified design shortcomings. 
Additionally, to maintain code coherence, it's needed to remove all methods associated with the field columnNames.

class location : lib/src/main/java/de/edux/data/provider/DataProcessor.java

**Comment by ANURAGSISODIYAA** [comment]
Hi there! 👋
I'm a beginner in open source, and I'm excited to contribute! I would like to work on this issue.

**Comment by acsolle66** [comment]
Hi @ANURAGSISODIYAA and welcome
I have assigned this task to you. Here is our <a href="https://github.com/Samyssmile/edux/wiki/Rules-&-Guidelines-for-New-Developers">Guideline for New Developers</a>. If you have any questions just ask. Additionally you can join our <a href="https://discord.gg/ARkK9wSN">discord server</a>.
