### ISSUE TITLE
Implement Brightness Augmentation

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#117]
We need an implementation of a BrightnessAugmentation class to adjust the brightness of images. This augmentation technique should be able to lighten or darken an image by a specified amount, enhancing our library's preprocessing capabilities for various machine learning tasks.

As orientation use already implemented Augmentations fro,

`package de.edux.augmentation.effects;
`

**Comment by sam-wmd** [comment]
Hi, @Samyssmile I would like to work on this issue
