### ISSUE TITLE
Maintain Aspect Ratio in the ResizeAugmentation Class

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#123]
The current implementation of the `ResizeAugmentation` class changes the width and height of the image independently, which can result in the loss of the image's aspect ratio if not carefully managed. This can lead to undesirable distortions, especially when the original aspect ratio is important.

We propose extending the `ResizeAugmentation` class to allow for the automatic maintenance of the aspect ratio. This would make it easier for users to resize the image while preserving the original aspect ratio.

- [ ] add constuctor with scale factor and ResizeQuality resizeQuality

**Comment by sam-wmd** [comment]
I could work on this

**Comment by Samyssmile** [comment]
@sam-wmd assigned to you
