### ISSUE TITLE
Implement Otsu's Thresholding Augmentation

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#169]
Otsu's method is a well-known algorithm in image processing used for automatic thresholding. The algorithm determines the threshold that minimizes the intra-class variance, effectively separating the foreground from the background. This method is particularly useful in scenarios where the histogram of the image exhibits a bimodal distribution, making it highly effective for a range of applications including document scanning, medical imaging, and preprocessing for further image analysis tasks.

[Original Image](https://en.wikipedia.org/wiki/Otsu%27s_method#/media/File:Image_processing_pre_otsus_algorithm.jpg)
[Otsu Image Example](https://en.wikipedia.org/wiki/Otsu%27s_method#/media/File:Image_processing_post_otsus_algorithm.jpg)

**Comment by gerasidev** [comment]
Hi @Samyssmile ,
[https://github.com/Samyssmile/edux/pull/170](url)
