### ISSUE TITLE
Replace filterIncompleteRecords boolean with Imputation Enum for Enhanced Data Handling

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#23]
There is an open discussion for this ticket. https://github.com/Samyssmile/edux/discussions/62
In our data processing logic, we currently use a boolean named **filterIncompleteRecords** to decide whether to filter out incomplete records or not. To provide more flexibility and future extensibility in handling missing data, we propose replacing this boolean with an enum named Imputation.

Let see on this example tiger dataset.
| Tiger            |    size           |    |
| ------------- | ------------- | ------------- |
| Syberian Tiger  | Big  |   ok  |
| Indian Tiger  | Small  |    ok   |
| Amur Tiger  |    |  Missed Value in dataset |

With **filterIncompleteRecords** = true, our Data Processing Class will **auto remove** Amur Tiger from the dataset, because the size value is **missed**.

The new Imputation enum would have various strategies such as MEDIAN, MODE, FILTEROUT, and AVERAGE. For the scope of this ticket, we'll focus on implementing FILTEROUT and AVERAGE, MODE.

# Advantages of this new Feature

A user can auto fill missed values.

# Hint
How filterIncompleteRecords works you can see in the Seaborn Pinguin k-nearest neighbors algorithm (knn) example.
https://github.com/Samyssmile/edux/blob/main/example/src/main/java/de/example/knn/KnnSeabornExample.java

**Comment by acsolle66** [comment]
I will take this ticket, gather my thoughts on how I would solve this, and present my idea.
