### ISSUE TITLE
 Refactoring Needed for Better Code Readability

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#25]
# Description:
In our codebase, there are numerous instances where one-line comments are used. While comments can be helpful, excessive usage can reduce the readability of the code. This ticket proposes the removal of these one-line comments and, where appropriate, extracting code blocks into self-explanatory methods.

Extract Code into Self-Explaining Methods:

For code blocks that are accompanied by comments to explain their logic, consider extracting them into separate methods.
Ensure that the new methods have descriptive names, effectively removing the need for the original comment.
For example, if there's a comment like // Check if user is valid, you can create a method named isValidUser().

**Comment by acsolle66** [comment]
Hi 
I have started to work on this issue and have a question. Should I do the clenup in the examples and in the lib/src/test folders too ?

**Comment by Samyssmile** [comment]
Yes, thanks
